### ISSUE TITLE
How to use stripHtmlTags and stripAttributes properties

### ISSUE THREAD

**Issue by tassu** [goldsky/spiefeed#15]
*Maybe wron place to ask this.

Try to strip <figure> tag and widht attribute from image in feed. I`ve tried every possible variation what I can think, but tag and attribute renders there. So how this should be done?

**Comment by vierkantemeter** [comment]
- Apply this patch - https://github.com/goldsky/spiefeed/pull/16/files if you using version 1.6.1 or prior
- Use   &stripHtmlTags=`table,tr,td,a`
